### ISSUE TITLE
Doesn't work with Swift 3

### ISSUE THREAD

**Issue by ahalmai** [quangtqag/WobbleBubbleButton#2]
Please, translate it!
Attila

**Comment by crashhh** [comment]
Did you translate the code?

**Comment by quangtqag** [comment]
Hi @crashhh,
I'll translate it in my weekend and available in next week

**Comment by ahalmai** [comment]
Hi, don't worry about that!
I've solved the problem.
Thank, Attila

**Comment by quangtqag** [comment]
Hi @ahalmai  and @crashhh,
I've just upgraded it to Swift 3. Give it a try.

**Comment by crashhh** [comment]
hey @quangtqag Why this doesnt work?
//btnmedium as wobble button
btnMedium.frame = CGRect(x: 0, y: 0, width: sizeOne, height: sizeOne)
I can change its size, but not the x and y position.

**Comment by iceman201** [comment]
@ahalmai Now it upgrades to swift 5

**Comment by quangtqag** [comment]
thanks @iceman201 for upgrading it to swift 5
